### ISSUE TITLE
Command.Connection always gets disposed when using FindAll, even when using a DelegatedDbConnection

### ISSUE THREAD

**Issue by ToJans** [ThatRendle/Simple.Data#18]
For the SQLite memory database we use a delegatedbconnection. The problem is that the connection gets disposed directly upon closing the IDataReader.

This is the relevant part

<pre>
// from Simple.Data.Ado.DbCommandExtensions.cs

        private static void DisposeCommandAndReader(IDbCommand command, IDataReader reader)
        {
            // by calling dispose on command.Connection, the delegateddbconnection is skipped
            using (command.Connection)
            using (command)
            using (reader)
            { /* NoOp */ }
        }
</pre>

**Comment by ThatRendle** [comment]
Fixed in source, release in next build.

**Comment by ToJans** [comment]
Thanks !

**Comment by ToJans** [comment]
AFAIK you forgot to change the "using (command.Connection) to using(connection)

**Comment by ThatRendle** [comment]
So I did. Fixed. Thanks!

**Comment by ToJans** [comment]
This works now! (I made a temporary fork for nerdbeers until @Notmyself has merged his changes.) Thanks for the fix !
